### ISSUE TITLE
add 1.20.3-4 support

### ISSUE THREAD

**Issue by c00ldude1oo** [LopyMine/SlashPortal#1]
```
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Slash Portal' (slash-portal) 1.0.0 with any version that is compatible with:
		 - minecraft 1.20.4
More details:
	 - Mod 'Slash Portal' (slash-portal) 1.0.0 requires version 1.20, version 1.20.1 or version 1.20.2 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.4!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.6.jar:?]
```

also modrinth claims 1.20.3+ support
![image](https://github.com/LopyMine/SlashPortal/assets/15677803/12bad9ff-9669-4737-909d-fc33255dce87)

**Comment by LopyMine** [comment]
Oops, will be fixed, thanks for issue

**Comment by LopyMine** [comment]
I think I should close this issue
